FROM continuumio/miniconda2:latest
MAINTAINER chienchi@lanl.gov

LABEL version="0.01"
LABEL software="NMDC_MAG_Pipeline"
LABEL tags="bioinformatics"

# Tell systemd we're running in Docker!

ENV container docker

RUN apt update && apt install -y gcc libidn11 procps gzip && \
    conda config --add channels defaults && \ 
    conda config --add channels conda-forge && \
    conda config --add channels bioconda && \
    conda config --add channels ursky && \
    mkdir -p /data && \
    mkdir -p /databases/checkM && cd /databases/checkM && \ 
    wget https://data.ace.uq.edu.au/public/CheckM_databases/checkm_data_2015_01_16.tar.gz && \ 
    tar xvzf checkm_data_2015_01_16.tar.gz && \
    rm checkm_data_2015_01_16.tar.gz && \
    conda install -y -c ursky metawrap-mg FaQCs idba minimap2 seqtk && \
    conda remove --force -y -c bioconda checkm-genome blast && \
    pip install --upgrade pip && \
    pip install checkm-genome==1.0.18 && \
    pip install --upgrade --force-reinstall matplotlib && \
    wget https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.9.0/ncbi-blast-2.9.0+-x64-linux.tar.gz && \
    tar xvzf ncbi-blast-2.9.0+-x64-linux.tar.gz && cp ncbi-blast-2.9.0+/bin/* /opt/conda/bin && \
    wget https://github.com/ruanjue/wtdbg2/releases/download/v2.5/wtdbg-2.5_x64_linux.tgz && \
    tar xvzf wtdbg-2.5_x64_linux.tgz && cp wtdbg-2.5_x64_linux/* /opt/conda/bin && \
    wget ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools/converters/by_program/tbl2asn/linux64.tbl2asn.gz && \
    gunzip linux64.tbl2asn.gz && chomd 755 linux64.tbl2asn && mv linux64.tbl2asn /opt/conda/bin/ && \
    apt autoremove -y && apt clean && \
    conda clean -y -a && rm -rf ncbi-blast-2.9.0* wtdbg-2.5_x64_linux* && \
    apt-get autoremove -y && apt-get clean && \
    ktUpdateTaxonomy.sh && \
    checkm data setRoot /databases/checkM  2>/dev/null && \
    chmod 777 /opt/conda/lib/python2.7/site-packages/checkm/DATA_CONFIG && \
    chmod -R 777 /databases/checkM 

COPY reassemble_bins.sh /opt/conda/bin/metawrap-modules/
COPY assembly.sh /opt/conda/bin/metawrap-modules/
COPY bin_refinement.sh /opt/conda/bin/metawrap-modules/
COPY config-metawrap /opt/conda/bin/

WORKDIR /data

CMD ["/bin/bash"]

